スダ宇宙を作りました
tonkotsuboy/suda pull request #13
Opened 2018-05-13 18:02 UTC by incolorsnet

スダのユニバースです。ご査収ください。どうぞよろしくお願いいたします。

2018-05-15 04:06 UTC, tonkotsuboy reviewed
コメントしました

2018-05-15 04:06 UTC, tonkotsuboy commented on docs/suda-universe/index.html
> +      let CAMERA_PARAM = {
全体的にですが、値を再代入しないならば`let`ではなく`const`宣言でいいかと。

2018-05-15 04:06 UTC, tonkotsuboy commented on docs/suda-universe/js/script.js
> +class SudaKorogashi {
これは不要ファイルな気が！

2018-05-15 04:23 UTC, yuukiit commented on docs/suda-universe/js/script.js
> +class SudaKorogashi {
ワァいろいろずさんすぎるのにレビューありがとうございます！！「すだころがしの派生だしPRしよ！」みたいな安易な気持ちでPRしたんですがこんなにがっつりレビューしていただけるとは思っていなくて恐縮しています！！
ウェブにあったコードを写経しつつ構造を理解しようとしていたのでゼロから書いたコードではないんですが、鹿野先生のレビューも含めてメチャメチャ勉強になりました〜〜〜！！😭😭😭
後ほど修正ファイルをPRします…笑　ありがとうございます！！

2021-04-26 07:56 UTC, tonkotsuboy requested changes
だめだだめだ！なっとらん！！

2021-04-26 07:59 UTC, tonkotsuboy approved these changes
フッ・・・やるじゃあねえか

2021-04-26 08:00 UTC, tonkotsuboy reviewed
ほほう？

2024-02-19 07:32 UTC, closed without merging